extends: default

rules:
  line-length:
    max: 120
  truthy:
    allowed-values: ["true", "false", "on"]
  document-start: disable
  comments:
    min-spaces-from-content: 1
  comments-indentation: disable
  braces:
    max-spaces-inside: 1
