
# Copy to tools/config.yaml for local runs (optional)
jira:
  base_url: "https://yourcompany.atlassian.net"
  user_email: "you@company.com"
  api_token: "SECRET"
  project_key_regex: "SECO-[0-9]+"  # or "(SECO|OPS)-[0-9]+"
transitions:
  in_review: "In Review"   # can be name or numeric id
  done: "Done"
